### ISSUE TITLE
Transfer screen

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum.UI.Wallet.Sample#2]
UX:
Navigate to Transfer screen
Select account from pick list, 
Select token from pick list
Display balance
Input amount
Input address
Submit
Prompt user for password
Display transactionId

**Comment by rraallvv** [comment]
Is this transfer screen already implemented?
I mean, does the wallet currently support transfers?
Keep up the good work.

**Comment by juanfranblanco** [comment]
Check this for the time being https://github.com/Nethereum/Nethereum.SimpleWindowsWallet or this https://github.com/Nethereum/Nethereum.UI.Desktop

**Comment by juanfranblanco** [comment]
@rraallvv  check the latest..
