### ISSUE TITLE
Update NethereumPortable.dll to actual version

### ISSUE THREAD

**Issue by Etrimus** [Nethereum/Nethereum.UI.Wallet.Sample#3]
Hello, thanks for this .net-implementation, i think, NethereumPortable library in Xamarin-example needs to be updated to latest version. Because there is no backward compatibility between rc-versions and latest stable.

**Comment by juanfranblanco** [comment]
I have updated it to the latest version of Nethereum, Xamarin, MvvmCross.. etc. I have made Infura the web3 client and put some "hardcoded" accounts as samples.
