### ISSUE TITLE
MvvmCross.Forms.Presenter not supported

### ISSUE THREAD

**Issue by ushakrishnan** [Nethereum/Nethereum.UI.Wallet.Sample#4]
Hello Juan,

Is there an update to this project, now that MvvmCross.Forms.Presenter is not supported anymore?

https://www.nuget.org/packages/MvvmCross.Forms.Presenter/

Thank you

**Comment by juanfranblanco** [comment]
Hi Usha,

Not yet, but the "refactoring" is to Prism. As it is simpler to extend / modify and add modules.

J

**Comment by ushakrishnan** [comment]
Thank you, Juan.

**Comment by juanfranblanco** [comment]
@ushakrishnan  Just ported everything to Netstandard and MvvmCross 5.0.2 (still not 5.3.0). I am evaluating again Prism vs MvvmCross as MvvmCross is moving along. Yet not convinced about modularity.
