### ISSUE TITLE
Invalid references in Nethereum.UI.Core

### ISSUE THREAD

**Issue by ValentinPetrovManolov** [Nethereum/Nethereum.UI.Wallet.Sample#5]
![nethereum ui core](https://user-images.githubusercontent.com/23012624/31557633-9bf633fc-b017-11e7-91d8-8aedeeb19904.jpg)

When I opened the project I had invalid references in the project Nethereum.UI.Core and was unable to fix them after playing with the newest versions etc.

**Comment by juanfranblanco** [comment]
I have ported everything to Netstandard, latest Nethereum 2.0.1, let me know how it goes.

**Comment by ValentinPetrovManolov** [comment]
now it compiles and works without problems
Thank you Juan!
Valentin

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by juanfranblanco** [comment]
Great :)
